//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContractItem
    {
        public int Id { get; set; }
        public string ContractNumber { get; set; }
        public string ItemCode { get; set; }
        public Nullable<double> ItemQuantity { get; set; }
        public string ItemInfo { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
