//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductionProposalDetail
    {
        public int Id { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<double> RecommendedNumberAB { get; set; }
        public Nullable<double> ChangedNumberAB { get; set; }
        public Nullable<double> RecommendedNumberCD { get; set; }
        public Nullable<double> ChangedNumberCD { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> ProductionProposalId { get; set; }
        public string ItemName { get; set; }
        public string ItemUnitName { get; set; }
    
        public virtual tblProductionProposal tblProductionProposal { get; set; }
    }
}
