//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductionPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProductionPlan()
        {
            this.tblProductionPlan1 = new HashSet<tblProductionPlan>();
            this.tblProductionProposals = new HashSet<tblProductionProposal>();
        }
    
        public int Id { get; set; }
        public string RefNumber { get; set; }
        public string Title { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> DayFrom { get; set; }
        public Nullable<System.DateTime> DayTo { get; set; }
        public string UnitName { get; set; }
        public Nullable<System.DateTime> PlanCreationDate { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string UpdateBy { get; set; }
        public bool IsDeleted { get; set; }
        public int Step { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductionPlan> tblProductionPlan1 { get; set; }
        public virtual tblProductionPlan tblProductionPlan2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductionProposal> tblProductionProposals { get; set; }
    }
}
