//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductionTimelineWeekly
    {
        public int Id { get; set; }
        public int ProductionTimelineID { get; set; }
        public Nullable<System.DateTime> DateOfManufacture { get; set; }
        public Nullable<int> Slot { get; set; }
        public string Stage { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual tblProductionTimeline tblProductionTimeline { get; set; }
    }
}
