//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHTD_SERVICES.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartner
    {
        public int Id { get; set; }
        public Nullable<int> PartnerGroupId { get; set; }
        public string PartnerId { get; set; }
        public string PartnerAccount { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsCustomer { get; set; }
        public Nullable<bool> IsProvider { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Manager { get; set; }
        public Nullable<int> ProviderType { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> CommuneId { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Note { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ZoneId { get; set; }
    }
}
